#Array Manipulation routines#

In [3]:
import numpy as np
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [6]:
y = x.reshape((3,2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [12]:
x = np.array([[0, 1, 2], [3, 4, 5]], dtype = np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [13]:
y = np.reshape(x,6)
print(y)

[0 1 2 3 4 5]


In [14]:
print(x)

[[0 1 2]
 [3 4 5]]


In [15]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [16]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


In [17]:
y = x.flatten('C')
print(y)

[0 1 2 3 4 5]


In [18]:
y = x.flatten('F')
print(y)

[0 3 1 4 2 5]


#How To Join MUltiple Array#

In [19]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5, 6], dtype = np.uint8)

print(x.dtype)

print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [20]:
z = np.stack((x,y))
print(z)


[[1 2 3]
 [4 5 6]]


In [21]:
z = np.stack((x,y), axis = 0)
print(z)

[[1 2 3]
 [4 5 6]]


In [22]:
z = np.stack((x,y), axis = -1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
z = np.stack((x,y), axis = -1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
z = np.dstack((x,y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [26]:
print(z.shape)

(1, 3, 2)


In [27]:
z = np.hstack((x,y))
print(z)

[1 2 3 4 5 6]


In [28]:
z = np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [29]:
print(z.shape)

(2, 3)


In [30]:
x = np.arange(9)
print(x)


[0 1 2 3 4 5 6 7 8]


In [31]:
a, b, c =np.split(x,3)
print(a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [32]:
x = np.random.rand(4, 4, 4)
print(x)

[[[0.95253734 0.25151055 0.65672332 0.52316993]
  [0.09336974 0.25168771 0.87414627 0.82205477]
  [0.04025251 0.90369663 0.53784119 0.90911198]
  [0.32180775 0.14835246 0.0237004  0.98349976]]

 [[0.68458332 0.48316497 0.20971799 0.18560527]
  [0.19916665 0.22263247 0.14592274 0.81348746]
  [0.65205757 0.67015669 0.63492745 0.49165893]
  [0.09026382 0.87924907 0.89016645 0.6461375 ]]

 [[0.55618308 0.73976406 0.80772211 0.22804626]
  [0.79545689 0.85442926 0.96196219 0.77724603]
  [0.9977485  0.21130175 0.35583029 0.73866804]
  [0.98802145 0.75196159 0.49938149 0.32754093]]

 [[0.32960183 0.77711014 0.67219783 0.17161429]
  [0.50853815 0.53272948 0.47570479 0.95845567]
  [0.60489181 0.43821869 0.62465111 0.24046244]
  [0.69451264 0.08945567 0.63280172 0.73404117]]]


In [34]:
y,z =np.split(x,2)
print(y, z)

[[[0.95253734 0.25151055 0.65672332 0.52316993]
  [0.09336974 0.25168771 0.87414627 0.82205477]
  [0.04025251 0.90369663 0.53784119 0.90911198]
  [0.32180775 0.14835246 0.0237004  0.98349976]]

 [[0.68458332 0.48316497 0.20971799 0.18560527]
  [0.19916665 0.22263247 0.14592274 0.81348746]
  [0.65205757 0.67015669 0.63492745 0.49165893]
  [0.09026382 0.87924907 0.89016645 0.6461375 ]]] [[[0.55618308 0.73976406 0.80772211 0.22804626]
  [0.79545689 0.85442926 0.96196219 0.77724603]
  [0.9977485  0.21130175 0.35583029 0.73866804]
  [0.98802145 0.75196159 0.49938149 0.32754093]]

 [[0.32960183 0.77711014 0.67219783 0.17161429]
  [0.50853815 0.53272948 0.47570479 0.95845567]
  [0.60489181 0.43821869 0.62465111 0.24046244]
  [0.69451264 0.08945567 0.63280172 0.73404117]]]


In [35]:
y,z =np.hsplit(x,2)
print(y, z)

[[[0.95253734 0.25151055 0.65672332 0.52316993]
  [0.09336974 0.25168771 0.87414627 0.82205477]]

 [[0.68458332 0.48316497 0.20971799 0.18560527]
  [0.19916665 0.22263247 0.14592274 0.81348746]]

 [[0.55618308 0.73976406 0.80772211 0.22804626]
  [0.79545689 0.85442926 0.96196219 0.77724603]]

 [[0.32960183 0.77711014 0.67219783 0.17161429]
  [0.50853815 0.53272948 0.47570479 0.95845567]]] [[[0.04025251 0.90369663 0.53784119 0.90911198]
  [0.32180775 0.14835246 0.0237004  0.98349976]]

 [[0.65205757 0.67015669 0.63492745 0.49165893]
  [0.09026382 0.87924907 0.89016645 0.6461375 ]]

 [[0.9977485  0.21130175 0.35583029 0.73866804]
  [0.98802145 0.75196159 0.49938149 0.32754093]]

 [[0.60489181 0.43821869 0.62465111 0.24046244]
  [0.69451264 0.08945567 0.63280172 0.73404117]]]


In [36]:
y,z =np.vsplit(x,2)
print(y, z)

[[[0.95253734 0.25151055 0.65672332 0.52316993]
  [0.09336974 0.25168771 0.87414627 0.82205477]
  [0.04025251 0.90369663 0.53784119 0.90911198]
  [0.32180775 0.14835246 0.0237004  0.98349976]]

 [[0.68458332 0.48316497 0.20971799 0.18560527]
  [0.19916665 0.22263247 0.14592274 0.81348746]
  [0.65205757 0.67015669 0.63492745 0.49165893]
  [0.09026382 0.87924907 0.89016645 0.6461375 ]]] [[[0.55618308 0.73976406 0.80772211 0.22804626]
  [0.79545689 0.85442926 0.96196219 0.77724603]
  [0.9977485  0.21130175 0.35583029 0.73866804]
  [0.98802145 0.75196159 0.49938149 0.32754093]]

 [[0.32960183 0.77711014 0.67219783 0.17161429]
  [0.50853815 0.53272948 0.47570479 0.95845567]
  [0.60489181 0.43821869 0.62465111 0.24046244]
  [0.69451264 0.08945567 0.63280172 0.73404117]]]


In [37]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
y = np.flip(x, axis = -1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [39]:
y = np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [40]:
y = np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [41]:
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [43]:
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [44]:
y = np.roll(x, 8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [46]:
y = np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
