In [1]:
import numpy as np 

In [4]:
x = np.random.randint(low = 0, high = 9, size = 10)
print(x)

[8 1 3 3 8 0 7 3 4 4]


In [5]:
x = np.random.rand(3, 3)
print(x)

[[0.99335455 0.61373702 0.28186816]
 [0.96949039 0.25239653 0.86964572]
 [0.00843897 0.77428108 0.87327809]]


In [6]:
x = np.random.rand(3, 3, 3)
print(x)

[[[0.72453324 0.23510649 0.6011388 ]
  [0.32740225 0.18002157 0.96221833]
  [0.11681948 0.15316186 0.82956499]]

 [[0.83278942 0.84862732 0.21717351]
  [0.05653758 0.67159207 0.53686143]
  [0.14731225 0.21579796 0.53308967]]

 [[0.18088546 0.13174724 0.39531191]
  [0.73755063 0.66246564 0.46767111]
  [0.1824682  0.15378645 0.24018941]]]


In [7]:
x = np.random.rand(2, 2, 2, 2, 2)
print(x)

[[[[[0.13859827 0.81663251]
    [0.10940866 0.49971897]]

   [[0.35643705 0.50982803]
    [0.90659036 0.86239468]]]


  [[[0.27300478 0.29249353]
    [0.83009293 0.5877686 ]]

   [[0.90965114 0.30413647]
    [0.42601327 0.3555431 ]]]]



 [[[[0.55766843 0.43534898]
    [0.8332037  0.96757941]]

   [[0.65777577 0.43962067]
    [0.64017446 0.76945255]]]


  [[[0.97288896 0.42392412]
    [0.94007934 0.79255091]]

   [[0.85574326 0.33178313]
    [0.07476132 0.53345721]]]]]
