In [1]:
import numpy as np
data = np.array([1, 2, 3, 3, 2, 1, 4, 5])
print(np.unique(data))

[1 2 3 4 5]


In [6]:
data = np.array([[1, 2, 3], 
             [3, 2, 1],
             [4, 5, 3]])
print(np.unique(data))

[1 2 3 4 5]


In [7]:
data = np.array([0, 1, 2, 3, 4,])
a = np.array([1, 2,]) 
print(np.in1d(data, a))

[False  True  True False False]


In [8]:
data1 = np.array([0, 1, 1, 3])
data2 = np.array([1, 2, 2, 3])
print(np.intersect1d(data1,data2))

[1 3]


In [9]:
print(np.setdiff1d(data1, data2))

[0]


In [10]:
#Minus operation/Set difference
print(np.setdiff1d(data2, data1))

[2]


In [11]:
print(np.setxor1d(data1, data2))

[0 2]


In [12]:
print(np.setxor1d(data1, data2))

[0 2]


In [14]:
print(np.union1d(data1, data2))

[0 1 2 3]
