In [1]:
import numpy as np
data = np.array([[1, 2, 3, 4],
                [3, 1, 2, 0]])
print(np.sort(data))

[[1 2 3 4]
 [0 1 2 3]]


In [2]:
print(np.sort(data, axis =0))

[[1 1 2 0]
 [3 2 3 4]]


In [3]:
print(np.sort(data, axis = 1))

[[1 2 3 4]
 [0 1 2 3]]


# Count Non Zero Element

In [6]:
data = np.array([[0, 2, 6, 0, 0],
                [4, 0, 0, 1, 56]])
print(np.count_nonzero(data))

5


In [5]:
print(np.count_nonzero(data, axis = 0))

[1 1 1 1 1]


In [7]:
print(np.count_nonzero(data, axis = 1))

[2 3]
