In [16]:
import numpy as np

#a = np.arange(10)#
#print(a)#

In [2]:
print(np.median(a))

4.5


In [3]:
print(np.average(a))

4.5


In [4]:
print(np.mean(a))

4.5


In [17]:
b = np.random.randint(low = 0, high = 10, size = 10)
print(b)

[7 6 8 6 3 7 6 8 5 0]


In [22]:
print(np.median(b))

6.0


In [21]:
print(np.average(b))

5.6


In [20]:
print(np.mean(b))

5.6


In [23]:
print(np.std(b))

2.33238075793812


In [24]:
print(np.var(b))

5.4399999999999995


In [25]:
print(np.histogram(b))

(array([1, 0, 0, 1, 0, 0, 1, 3, 2, 2], dtype=int64), array([0. , 0.8, 1.6, 2.4, 3.2, 4. , 4.8, 5.6, 6.4, 7.2, 8. ]))


In [26]:
x = np.array([[[1, 2, 3], [4, 5, 6]], [[0, -1, -2], [-3, -4, -5]]], np.int16)
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [28]:
print(np.mean(x))

0.5


In [29]:
print(np.std(x))

3.452052529534663


In [30]:
print(np.var(x))

11.916666666666666


In [31]:
print(np.median(x))

0.5


In [33]:
print(np.average(x))

0.5
