In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
a = np.arange(1,101)

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

### Split the data

In [5]:
train_test_split(a)
a=()

[array([ 28,  15,   9,  29, 100,  78,  52,  66,  26,  73,  75,   7,  43,
         85,  31,  80,  17,  23,   8,   2,  27,   5,  98,  70,  91,  74,
         20,  60,  93,  59,  81,  53,  39,   1,  62,  42,  24,   4,  55,
         45,  54,  96,  46,  16,  69,  34,  87,  50,  68,  32,  71,  79,
         58,  51,  65,  33,  56,  92,  49,  38,  10,  99,  82,  25,  12,
         19,  97,   6,  30,  90,  86,  57,  37,  84,  13]),
 array([22, 48, 89, 83, 21, 36, 40, 77, 41, 88, 72, 64, 47, 94,  3, 35, 44,
        76, 95, 67, 61, 18, 11, 14, 63])]