In [1]:
import numpy as np

In [2]:
n1 = np.array([[5,12,6],[-3,0,14]])
n1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
n2 = np.array([[9,8,7],[1,3,-5]])
n2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
n1 + n2

array([[14, 20, 13],
       [-2,  3,  9]])

In [7]:
m1 = np.array([[5,3],[-2,4]])
m2 = np.array([[7,-5],[3,8]])

In [8]:
m1

array([[ 5,  3],
       [-2,  4]])

In [9]:
m2

array([[ 7, -5],
       [ 3,  8]])

In [10]:
m1 - m2

array([[-2,  8],
       [-5, -4]])

In [11]:
m3 = np.array([[22.33, -4.73],[-203.14, 1200.02],[4.22, 234.10]])
m3

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [13]:
m4 = np.array([[133.13, 448.29],[-340.21, 1.06],[30.41, 424.99]])
m4

array([[ 133.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [14]:
m3 - m4

array([[-110.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

### adding vectors

In [18]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [19]:
v1 + v2

array([6, 6, 6, 6, 6])

In [20]:
v1- v2

array([-4, -2,  0,  2,  4])

### Transposing matrices