In [1]:
import numpy as np

### Declaring scalars,vectors, and matrices

In [2]:
s = 5

In [3]:
s

5

In [8]:
v = np.array([5,2,4])

In [9]:
v

array([5, 2, 4])

In [14]:
n = np.array([[5,12,6],[-3,0,14]])

In [15]:
n

array([[ 5, 12,  6],
       [-3,  0, 14]])

### data type

In [16]:
type(s)

int

In [19]:
type(v,)

numpy.ndarray

In [21]:
s_array = np.array(5)
s_array

array(5)

In [22]:
type(s_array)

numpy.ndarray

### Data shapes

In [25]:
n.shape

(2, 3)

In [26]:
v.shape

(3,)

### creating a vector

In [27]:
v.reshape(1,3)


array([[5, 2, 4]])

In [28]:
v.reshape(3,1)

array([[5],
       [2],
       [4]])